### PR TITLE
Update  README and other changes

### PR DESCRIPTION
**Pull request by Klortho**
@danizen, the main thing here is updates to the README file.  While testing, I made some minor cahnges to the script mesh-xml2rdf.sh, and I updated the samples files.

### CODE REVIEW

**Comment by danizen** [comment]
I like everything except the cd into $MESHRDF_HOME.   Some sort of cd is needed if mesh-xml2rdf.sh is called from someplace other than /usr/nlm/mesh.   It can be done in the calling script for nightly processing.    We can also do something self-relative with dirname and readlink, but then the script gets more complicated.

**Comment by Klortho** [comment]
I took that out because MESHRDF_HOME isn't necessarily the same as the base directory of the repository. The readme specifically mentions that they might be different, and the reason is that the data files are so large, it allows them to be stored on some other filesystem.

We could use perl's [FindBin](http://perldoc.perl.org/FindBin.html) to `cd $FindBin::Bin/..`.  What do you think?

**Comment by danizen** [comment]
Ah, but `cp meta/...` will not work without a cd.   And using `$MESHRDF_HOME/meta/...` will not work unless `MESHRDF_HOME/meta` is installed.    Since `mesh-xml2rdf.sh` is 

How about:
```
# Default to parent directory
if [ -z "$MESHRDF_HOME" ]; then
    export MESHRDF_HOME=$(readlink -e `dirname $0`)/..
fi
```

Might also require change to `/bin/bash`

**Comment by Klortho** [comment]
What's really need are separate MESHRDF_HOME and MESHRDF_DATA.

Why not just cd to the script directory?

```
if hash greadlink 2>/dev/null; then
    READLINK=greadlink
else
    READLINK=readlink
fi
...
cd $($READLINK -e `dirname $0`)
```

Will that work?

**Comment by danizen** [comment]
I like that solution.   Then we'll be copying from ../meta/ into $OUTDIR

**Comment by Klortho** [comment]
Okay, I added it, and it seems to work.

**Pull request merged**
