### PR TITLE
Meshrdf klortho

### PR DESCRIPTION
**Pull request by Klortho**
Changes for the XSLTs.  Per @davidanderson3 , we probably don't want these to go into master until we have updated the data that we are serving.

### CODE REVIEW

**Comment by danizen** [comment]
In 3a2325d98858dda730d8c39aeef508a42cde933d, you add sort -u for issue 108.   I think that -T"$MESHRDF_HOME/out" should be used instead.   The first time I did this, I ran out of space in /tmp.

**Comment by Klortho** [comment]
Sounds good to me.  I wasn't aware of this option. Do you want to update this PR?

**Comment by danizen** [comment]
I've updated the PR - I also found that gzip -k didn't work for me.   Perhaps running Ubuntu at home or on laptop, mmm?

**Comment by Klortho** [comment]
Looks good.

**Comment by danizen** [comment]
@Klortho, I think `meshrdf-klortho` be re-based on `meshrdf-dev`, and then a new pull request generated, and then merged.   I also have `meshrdf-klortho-danizen` which contains changes to parameterize the MESH ftp-uri, year, and prefix used for triple generation.

**Comment by Klortho** [comment]
@danizen , you are right.  I've merged meshrdf-klortho-danizen already, so I'll reopen this as a PR to meshrdf-dev.

**Pull request closed without merging**
